#define INT 1
#define FLOAT 2
#define CHAR 3
#define DOUBLE 4
#define VOID 5
#define STRING 6
#define BOOL 7
#define PLUS 8
#define MINUS 9
#define MULTIPLY 10
#define DIVIDE 11
#define MODULO 12
#define INCREMENT 13
#define DECREMENT 14
#define GREATER 15
#define LESS 16
#define GREATER_EQUAL 17
#define LESS_EQUAL 18
#define EQUAL 19
#define NOT_EQUAL 20
#define AND 21
#define OR 22
#define NOT 23
#define ASSIGN 24
#define IF 25
#define ELSE 26
#define SWITCH 27
#define CASE 28
#define DEFAULT 29
#define CONTINUE  30
#define BREAK 31
#define THEN 32
#define WHILE 33
#define DO 34
#define FOR 35
#define RETURN 36
#define REPEAT 37
#define UNTIL 38
#define TRUE 39
#define FALSE 40
#define LEFT_CURLY_BRACE 41
#define RIGHT_CURLY_BRACE 42
#define LEFT_PARENTHESIS 43
#define RIGHT_PARENTHESIS 44
#define LEFT_SQUARE_BRACKET 45
#define RIGHT_SQUARE_BRACKET 46
#define ENUM 47
#define FUNCTION 48
#define MAIN 49
#define PRINT 50
#define SCAN 51
#define IDENTIFIER 52 
#define DIGIT 53
#define FLOAT_LITERAL 54
#define STRING_LITERAL 55
#define CHAR_LITERAL 56
#define COMMENT 57
